### PR TITLE
Add ibuffer-vc-buffer-file-name-function option

### PR DESCRIPTION
**Pull request by tsilvap**
This is one way of fixing #25. To recap the issue: 

### Expected behavior
Only file buffers, "directory buffers" (e.g. Dired buffers), and other VC-related buffers (e.g. Magit buffers) should show up in the VC groups. Examples of buffers that should *not* show up are: ERC, Gnus, `*Help*`, `*info*`, or any other buffer at all that is not related to that VC directory.

### Actual behavior
If you're visiting a VC-controlled file, and you open an unrelated buffer such as those from ERC, or Gnus, or a `*Help*` buffer, etc., it'll show up in the VC group (because the buffer's `default-directory` will point to a VC-controlled directory).

### Proposed solution

@c-alpha's suggestion in the issue thread works great but it excludes e.g. Dired and Magit buffers, which IMO should go in the VC filter group too. And other people may have other preferences. But right now I don't think we can customize that since `ibuffer-vc-include-function`takes a filename, instead of a buffer.

If we introduce a new `ibuffer-vc-include-buffer-function`  option that takes a buffer instead, the user can have more control. e.g. I could implement the expected behavior with:

```elisp
(setq ibuffer-vc-include-buffer-function
      (lambda (buf)
        (with-current-buffer buf
          (or buffer-file-name
              list-buffers-directory)))) ; this is set by Dired buffers, Magit, VC dir, etc.
```

### CODE REVIEW

**Comment by tsilvap** [comment]
Hey @purcell, thanks for the feedback. Your suggestion makes sense to me, I just force-pushed a commit that implements it. Let me know if I misunderstood what you meant.

**Comment by purcell** [comment]
That does sound like a better default, yes. I think we should give that a go.

**Comment by tsilvap** [comment]
Sure thing. I force-pushed a new commit that changes the default behavior to that instead.

Hopefully users will agree that this is a better default and find it more useful, but if the old behavior is preferred, it can be restored by customizing the new `ibuffer-vc-buffer-file-name-function` variable, like so:

```elisp
(setq ibuffer-vc-buffer-file-name-function
      (lambda (buf)
        (with-current-buffer buf
          (file-truename (or buffer-file-name
                             default-directory)))))
```

**Comment by purcell** [comment]
Merged, thanks!

**Comment by purcell** [comment]
This feels like how things should always have been, thanks for the fix.

**Pull request merged**
