### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by manuel-uberti**
Just a minor fix for a minor typo. :)

### CODE REVIEW

**Comment by purcell** [comment]
Haha, this is the third time this has been reported, but it's actually not a typo. :-)

**Comment by purcell** [comment]
https://en.wikipedia.org/wiki/If_and_only_if

**Comment by manuel-uberti** [comment]
Oh I see, sorry about that. :)

**Comment by purcell** [comment]
To be honest, it's probably not worth the trouble to keep it...

**Comment by tsilvap** [comment]
FWIW, the GNU Emacs Lisp Reference Manual agrees that it's not worth the trouble to use "iff" in docstrings:
> - Avoid using “iff” (a mathematics term meaning “if and only if”), since many people are unfamiliar with it and mistake it for a typo. In most cases, the meaning is clear with just “if”. Otherwise, try to find an alternate phrasing that conveys the meaning. — [(elisp) Documentation Tips](https://www.gnu.org/software/emacs/manual/html_node/elisp/Documentation-Tips.html)

**Pull request closed without merging**
